version: "3.9"

services:
  # MinIO para almacenamiento S3 local
  minio:
    image: minio/minio:latest
    container_name: text-image-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console Web UI
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Servicio Text-to-Image
  text-image-api:
    build: .
    container_name: text-image-api
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    depends_on:
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  minio_data:
    driver: local
